# Generated by Django 5.2.3 on 2025-07-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='No subject', max_length=150),
            preserve_default=False,
        ),
    ]
